### ISSUE TITLE
top position behaviour different in firefox vs non suported browsers

### ISSUE THREAD

**Issue by iwebnaut** [wilddeer/stickyfill#63]
I want the sticky to be offset from the top of browser by 20 px, so I do top: 20px, this works fine in firefox but in chrome for example sticky is also offset inside it's parent, so it does not line up with siblings correctly, when scrolling down the sticky reaches the top and it's correctly offset 20px but the problem is initial state before scrolling is different then behaviour in firefox.

Is this a bug or do I need to initialize it differently?

**Comment by KaduAmaral** [comment]
I've a similar problem, I'm using `position: sticky` and is everything a paradise on Chrome.

Site structure...

```text
____________________________________
|          My Fixed Header         | height: 110px
|----------------------------------|
|          My Sticked Element      | is inside site-body and must stay on top
|----------------------------------|
|          My Site Body            | others elements on site-body
|                                  |
|__________________________________|
```

The problem is Internet Explorer, The Sticked Element are staying over the header. How can I pass a position for Stickyfill? Something like:
```javascript
Stickyfill.add(element, {top: '110px'});
```

**Comment by wilddeer** [comment]
Sorry for the late reply, I didn’t have much time to work on my personal projects lately.

@iwebnaut my guess is that you have `position: relative` set to one of the ancestors of your sticky element. If this issue is still relevant, please provide a live reproduction (link to the site/codepen/jsfiddle).

@KaduAmaral I need a live reproduction of this to help you.
