### ISSUE TITLE
Alignment issues when "top" is set in javascript

### ISSUE THREAD

**Issue by sam-dupras** [wilddeer/stickyfill#80]
updating the `top` property in javascript after `window.resize` will result in alignment issues even though I call `refreshAll`

In this example I offset the top by the window size and the element height, all works well until you resize the window. (the front of the car should stick to the bottom of the screen, this will not be the case after resizing) 

example: https://codepen.io/anon/pen/EweRYV

tested in edge on windows 10

**Comment by wilddeer** [comment]
This is because you modify the `top` value directly on the active sticky, then you call `refreshAll` and Stickyfill deactivates the sticky restoring its original `top` value, then activates it again.

There’s a workaround for this: deactivate the sticky, make whatever changes you need, then activate it again.

Here’s a fixed pen https://codepen.io/anon/pen/PJdLYg

**Comment by sam-dupras** [comment]
Thanks!
